name: numbertrivia
description: A simple number trivia app to learn more from flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^4.0.2
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  dartz: ^0.9.1
  connectivity: ^0.4.8+6
  http: ^0.12.1
  shared_preferences: ^0.5.7+3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


flutter:

  uses-material-design: true
